### ISSUE TITLE
@AfterOriginalMethod

### ISSUE THREAD

**Issue by cacker** [seebye/XClasses#2]
···
				else if(AnnotationUtils.isAfterMethodHook(method))
				{
					// this method should be called after the original method was called

					// first parameter should be objectResultUntilNow, we need to remove it from our list
					// unfortunately we can't check whether we forgot the parameter or not..
					// (as we want to allow every type for an comfortable usage)
					aParameterTypes = new ArrayList<>(Arrays.asList(method.getParameterTypes()));
					aParameterTypes.remove(0);
···

hi
Why would you call “aParameterTypes.remove(0)”, I have read the notes, but I'm not very clear.

Looking forward to your answer, the great project。

**Comment by cacker** [comment]
oh no
I test remove “aParameterTypes.remove(0)”, found all faild。

**Comment by cacker** [comment]
@seebye 
@AfterOriginalMethod not available, prompt wrong parameters

**Comment by seebye** [comment]
Don't remove “aParameterTypes.remove(0)”.
XClasses passes an additional parameter to "@AfterOriginalMethod"-methods, the result of the original method.
```java
@AfterOriginalMethod
private void hookedMethod_After(Object resultOfTheOriginalMethod
, /*Arguments of the orignal method*/) {}
```

As a method is uniquely defined by it's name and parameters
we need to remove the first parameter of "@AfterOriginalMethod"-methods
in order to find the original method inside of the original class.

If you remove this line you won't be able to create "@AfterOriginalMethod"-hook.

**Comment by cacker** [comment]
thank you   good work
i very like the project
